EVENTS/EVENTS/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required

from REGISTRO import views

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^busqueda', views.busqueda),
    
    #/*SISTEMA DE LOGIN COMPLETO*/
    url(r'^login/$', login, {'template_name': 'index.html', }, name="login"),
    url(r'^logout/$', logout, {'template_name': 'logout.html', }),
    url(r'^signup/$', 'HOME.views.signup', name='signup'),
    #/*FIN*/

    #/*SISTEMA PARTE DEL INICIO*/
    url(r'^$', 'HOME.views.home', name='home'),
    url(r'^home/$', 'REGISTRO.views.home_auth', name='home_auth'),
    url(r'^eventos/nuevo/$', views.CreateEventView.as_view(), name='crear_evento'),
    # url(r'^eventos/(?P<pk>\d+)/editar/$', views.UpdateEventView.as_view(), name='editar_evento'),
    url(r'^eventos/$', views.ListEventView.as_view(), name='listar_eventos'),
    url(r'^eventos/(?P<pk>\d+)/eliminar/$', views.eliminar_evento, name='eliminar_evento'),
    #/*FIN*/

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EVENTS/HOME/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-



from django.db import models

# Create your models here.

##class login(models.Model):
##	username = models.CharField(max_length=25, null=True)
##	password = models.CharField(max_length=25, null=True)
##	email = models.CharField(max_length=25, null=True)
##	first_name = models.CharField(max_length=25, null=True)
##	last_name = models.CharField(max_length=25, null=True)
##
##	def __str__(self):
##		return username		

EVENTS/REGISTRO/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-



from django.db import models
from django.contrib.auth.models import User


class Departamento (models.Model):
	nombre = models.CharField(max_length=30)

	def __str__(self):
		return self.nombre


class Ciudad (models.Model):
	nombre = models.CharField(max_length=30)
	departamento = models.ForeignKey(Departamento)

	def __str__(self):
		return self.nombre


class Evento (models.Model):
	nombre = models.CharField(max_length=30)
	descripcion = models.CharField(max_length=300)
	fecha = models.DateField()
	hora = models.TimeField()
	lugar = models.CharField(max_length=30)
	ciudad = models.ForeignKey(Ciudad)
	usuario = models.ForeignKey(User)
	imagen =models.FileField(upload_to='media/', blank=True, null=True)
	#imagen =models.ImageField(upload_to='images/', blank=True, null=True)
	def __str__(self):
		return self.nombre


class Organizador (models.Model):
	nombre = models.CharField(max_length=30)
	email = models.EmailField()
	ciudad = models.ForeignKey(Ciudad)
	evento = models.ForeignKey(Evento)

	def __str__(self):
		return self.nombre

EVENTS/HOME/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
 
 
class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {'password': forms.PasswordInput()}

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Current Password', 'autocomplete': 'off'}))

    new_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'New Password', 'autocomplete': 'off'}))

    confirm_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirm New Password', 'autocomplete': 'off'}))

EVENTS/HOME/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.template import Context
from django.template.loader import get_template
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.utils import timezone
from REGISTRO.models import *
from .forms import *

# Create your views here.

def signup(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = SignUpForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
 
            # Process the data in form.cleaned_data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
 
            # At this point, user is a User object that has already been saved
            # to the database. You can continue to change its attributes
            # if you want to change other fields.
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
 
            # Save new user attributes
            user.save()
            return HttpResponseRedirect('/login/')    
            #return HttpResponseRedirect(reverse('main.html'))  # Redirect after POST
    else:
        form = SignUpForm()
        
    data = {
        'form': form,
    }
    return render_to_response('signup.html', data, context_instance=RequestContext(request))

def home(request):
    eventos = Evento.objects.order_by('-fecha')[:15]
    context = {
        'eventos':eventos
    }
    return render_to_response('home.html', context)    

EVENTS/templates/event_list.html
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" href="/static/css/estilos.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>   
<body>
<center><h1 class="animated zoomInDown" style="font-size: 50px; font-family: Roboto; text-align: center; color: #eee; text-shadow: 1px 1px #303F9F, 2px 2px #303F9F, 3px 3px #303F9F, 4px 4px #303F9F, 5px 5px #303F9F, 6px 6px #303F9F, 7px 7px #303F9F, 8px 8px #303F9F, 9px 9px #303F9F,
    10px 10px #303F9F; margin-top: 5px;">MIS EVENTOS</h1></center><br><br>    

<br>
<ul>
    {% if user.is_authenticated %}
    {% for evento in evento_list %}
    {% if evento.usuario == user%}
         
            <li>
        
                <p>{{ evento.nombre|upper }}</p>
       
                <p>
                    <a href="{% url "eliminar_evento" evento.id %}">Borrar</a> 
                </p>
            </li>
    {% endif %}    
    {% endfor %}
    {% endif %}
</ul><br>

<center><p>
   <a href="{% url "crear_evento" %}">>>>Agregar Evento<<<</a>
</p><br>
<a href={% url "home_auth" %}>Volver</a></center>

</body> 
</html>

EVENTS/templates/evento_confirm _delete.html
<form method="post">{% csrf_token %}
¿Estás seguro que deseas borrar la tarea "{{ eventos.nombre }}"?
<input type="submit" value="Aceptar" />
</form>
<p>
<a href="{% url "eventos:list" %}">Regresar</a>
</p>

EVENTS/templates/evento_detail.html
<h1>{{ eventos.name }}</h1>

<p>{{eventos.descripcion}}</p>
<p>
	<a href="{% url "eventos:list" %}">Regresar</a>
</p>

EVENTS/templates/evento_form.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  
  <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
  <link rel="stylesheet" href="/static/css/estilos.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	<title>Mis eventos</title>
</head>
<body>
<center><h1 class="animated zoomInDown" style="font-size: 50px; font-family: Roboto; text-align: center; color: #eee; text-shadow: 1px 1px #303F9F, 2px 2px #303F9F, 3px 3px #303F9F, 4px 4px #303F9F, 5px 5px #303F9F, 6px 6px #303F9F, 7px 7px #303F9F, 8px 8px #303F9F, 9px 9px #303F9F,
    10px 10px #303F9F; margin-top: 5px;">CREAR EVENTO :)</h1></center><br><br>  	
<center><form class="formulario" method="post" enctype='multipart/form-data'>{% csrf_token %}
  Nombre:<br>
  <input type="text" name="nombre" placeholder="nombre del evento"><br>
  Descripción:<br>
  <input type="text" name="desc" placeholder="Describe el evento"><br>
  Fecha:<br>
  <input type="date" name="fecha" value=""><br>
  Hora:<br>
  <input name="hora" type="time"></input><br>
  Ciudad:<br>
  <select name="ciudad">
  	{% for ciudad in data %}
  		<option value="{{ciudad.pk}}">{{ciudad.nombre}}</option>
  	{% endfor%}
  </select><br>
  Lugar:<br>
  <input name="lugar" type="text" placeholder="Lugar del evento"></input><br>
  Imagen:<br>
  <input name="imagen" type="file"><br><br>
  <input type="submit" value="Guardar">
</form>
<br>
<a href="/eventos/">>>>Volver<<<</a></center>
</body>
</html>

EVENTS/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/Events.css">

	<title>{% block title %}Tenemos eventos para ti{% endblock %}</title>
	
</head>
<body id="bg" style="background-image: url(/static/img/ff.jpg)";>  
    <nav class="navbar navbar-default">
    {% block usertools %}
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Events.co</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="#">¡Publicar un Evento!</a></li>
                <li><a href="/logout/">Logout</a></li>
                {% else %}
                <li><a href="/login/">Iniciar Sesion</a></li>
                <li><a href="/signup/">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    {% endblock %}
    </nav>

    {% block content %}
    <div class="text-center">
        <img src="/static/img/final.jpg"  alt="Hola :)" width="700" height="300">
    
    </div>
     <br>
    <form action="/busqueda" method="GET">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div id="imaginary_container"> 
                        <div class="input-group stylish-input-group">
                            
                            <input name="q" id="buscador" type="text" class="form-control"  placeholder="Escribe el nombre de una ciudad :)" style="width:100%; height:40px; font-size:18px">
                            <span class="input-group-addon">
                                <button type="submit" style="width:50px; height:0px">
                                    <span class="glyphicon glyphicon-search"></span>
                                 </button> 
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <br>
   
    <h1>Próximos eventos:</h1>  
    <div class="fondo_texto"> 
    {% for evento in eventos %}
        <h2>{{ evento.nombre }}</h2>
        <p><img src="{% if evento.imagen %}{{ evento.imagen.url}}{% endif %}" style="width:499px; height:200px;" class="img-responsive"></p>
        <br>
        
        <p><b>Descripción: </b>{{ evento.descripcion }}</p>
        <p><b>Fecha: </b>{{ evento.fecha }}</p>
        <p><b>Hora: </b>{{ evento.hora }}</p>
        <p><b>Lugar: </b>{{ evento.lugar }}</p>
        <p><b>Ciudad: </b>{{ evento.ciudad }}</p>
        <p><b>Reservar entrada: </b>
            <form>
                <script src="https://s3-us-west-2.amazonaws.com/epayco/v1.0/checkoutEpayco.js" 
                    class="epayco-button" 
                    data-epayco-key="491d6a0b6e992cf924edd8d3d088aff1" 
                    data-epayco-amount="50000" 
                    data-epayco-name="Vestido Mujer Primavera" 
                    data-epayco-description="Vestido Mujer Primavera" 
                    data-epayco-currency="cop" 
                    data-epayco-country="co" 
                    data-epayco-test="true"
                    data-epayco-response="https://ejemplo.com/respuesta.html" 
                    data-epayco-confirmation="https://ejemplo.com/confirmacion" >
                </script>
            </form>
        </p>
    {% endfor %}
    {% endblock %}
    <br><br><br>
    {% block footer %}
    <nav class="navbar navbar-default  navbar-fixed-bottom" role="navigation">
        <div class="container text-center">
            <p class="navbar-text col-md-12 col-sm-12 col-xs-12">Events.co 2017 &copy; </p>
        </div>
    </nav>
    
    </div>
    {% endblock %}

	{% block js %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
    <script
	  src="https://code.jquery.com/jquery-3.1.1.min.js"
	  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
	  crossorigin="anonymous">
    </script>
    {% endblock %}
   
</body>
</html>

EVENTS/templates/home_logout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/Events.css">

	<title>{% block title %}Tenemos eventos para ti{% endblock %}</title>
	
</head>
<body id="bg" style="background-image: url(/static/img/ff.jpg)";>  
    <nav class="navbar navbar-default">
    {% block usertools %}
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Events.co</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/eventos/">¡Publicar un Evento!</a></li>
                <li><a href="/logout/">Logout</a></li>
            </ul>
        </div>
    {% endblock %}
    </nav>

    {% block content %}
    <div class="text-center">
        <img src="/static/img/final.jpg"  alt="Hola :)" width="700" height="300">
    
    </div>
     <br>
    <form action="/busqueda" method="GET">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div id="imaginary_container"> 
                        <div class="input-group stylish-input-group">
                            
                            <input name="q" id="buscador" type="text" class="form-control"  placeholder="Escribe el nombre de una ciudad :)" style="width:100%; height:40px; font-size:18px">
                            <span class="input-group-addon">
                                <button type="submit" style="width:50px; height:0px">
                                    <span class="glyphicon glyphicon-search"></span>
                                 </button> 
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <br>
   
    <h1>Próximos eventos:</h1>  
    {% for evento in eventos %}
        <h2>{{ evento.nombre }}</h2>
        <p><img src="{{ evento.imagen.url}}" style="width:499px; height:200px;" class="img-responsive"></p>
        <br>
        <p><b>Descripción: </b>{{ evento.descripcion }}</p>
        <p><b>Fecha: </b>{{ evento.fecha }}</p>
        <p><b>Hora: </b>{{ evento.hora }}</p>
        <p><b>Lugar: </b>{{ evento.lugar }}</p>
        <p><b>Ciudad: </b>{{ evento.ciudad }}</p>
    {% endfor %}
    {% endblock %}
    <br><br><br><br>
    {% block footer %}
    <nav class="navbar navbar-default  navbar-fixed-bottom" role="navigation">
        <div class="container text-center">
            <p class="navbar-text col-md-12 col-sm-12 col-xs-12">Events.co 2017 &copy; </p>
        </div>
    </nav>
    
    </div>
    {% endblock %}

	{% block js %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
    <script
	  src="https://code.jquery.com/jquery-3.1.1.min.js"
	  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
	  crossorigin="anonymous">
    </script>
    {% endblock %}
   
</body>
</html>

EVENTS/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" href="/static/css/estilos.css">
	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	<title>| EVENTS | LOGIN |</title>
</head>
<body>
	<center><h1 class="animated zoomInDown" style="font-size: 50px; font-family: Roboto; text-align: center; color: #eee; text-shadow: 1px 1px #303F9F, 2px 2px #303F9F, 3px 3px #303F9F, 4px 4px #303F9F, 5px 5px #303F9F, 6px 6px #303F9F, 7px 7px #303F9F, 8px 8px #303F9F, 9px 9px #303F9F,
    10px 10px #303F9F; margin-top: 5px;">LOGIN EVENTS</h1></center>
	<div class="contenedor-formulario animated flipInX">
		<div class="wrap">
		{% block content %}
			<form class="formulario" method="post" action="{% url 'django.contrib.auth.views.login' %}">
			{% csrf_token %}
				<div>
					<div class="input-group">
						<input placeholder="Usuario" type="text" id="id_username" name="username" required="El campo contraseña es obligatorio" autocomplete="off">
					</div>
					<div class="input-group">
						<input placeholder="Contraseña" type="password" id="id_password" name="password" required="El campo contraseña es obligatorio" autocomplete="off">
					</div>
					<input type="submit" value="Ingresar">
        			<input type="hidden" name="next" value="{{ next }}">
				</div>
				{% if form.errors %}
        		<p style="text-align: center; color: #333;">Su nombre de usuario y contraseña no coinciden. Por favor, inténtelo de nuevo.</p>
        		{% endif %}
			</form>
		{% endblock  %}	
		</div>
	</div>

	<script src="/static/js/formulario.js"></script>
</body>
</html>

EVENTS/templates/logout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="robots" content="NONE,NOARCHIVE">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    
    <link rel="stylesheet" type="text/css" href="/static/css/estilos.css">
    <link rel="stylesheet" href="/static/css/logout.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <title>| EVENTS | LOGOUT |</title>
</head>
<body data-admin-utc-offset="-14400">
    <div class="contenedor" style="background: #303F9F;">
        <h1 class="animated lightSpeedIn">Sesión terminada</h1>
    </div>
    <div class="subcontenedor">
        <br><br>
        <p class="animated tada" id="mensaje" >Gracias por el tiempo que ha dedicado hoy al sitio web.</p>
        <br><br>
        <center><a href="/" class="animated swing" style="background: #303F9F;">Iniciar sesión de nuevo</a></center>
    </div>    
</body>
</html>

EVENTS/templates/signup.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" href="/static/css/estilos.css">
	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	<title>| EVENTS | SIGNUP |</title>
</head>
<body>
	
	<center><h1 class="animated zoomInDown" style="font-size: 50px; font-family: Roboto; text-align: center; color: #eee; text-shadow: 1px 1px #303F9F, 2px 2px #303F9F, 3px 3px #303F9F, 4px 4px #303F9F, 5px 5px #303F9F, 6px 6px #303F9F, 7px 7px #303F9F, 8px 8px #303F9F, 9px 9px #303F9F,
    10px 10px #303F9F; margin-top: 5px;">REGISTRO DE USUARIOS EVENTS</h1></center>
	<div class="contenedor-formulario animated flipInX">
		<div class="wrap">
		{% block content %}
			<form class="formulario" method="post" action="{% url 'signup' %}">
			{% csrf_token %}
				<div>
					<div class="input-group">
						<input placeholder="Nombre" type="text" id="id_first_name" name="first_name" required="El campo nombre es obligatorio" autocomplete="off">
					</div>
					<div class="input-group">
						<input placeholder="Apellido" type="text" id="id_last_name" name="last_name" required="El campo apellido es obligatorio" autocomplete="off">
					</div>
					<div class="input-group">
						<input placeholder="Email" type="email" id="id_email" name="email" required="El campo email es obligatorio" autocomplete="off">
					</div>
					<div class="input-group">
						<input placeholder="Usuario" type="text" id="id_username" name="username" required="El campo usuario es obligatorio" autocomplete="off">
					</div>
					<div class="input-group">
						<input placeholder="Contraseña" type="password" id="id_password" name="password" required="El campo contraseña es obligatorio" autocomplete="off">
					</div>
					<input type="submit" value="Registrar" onclick='alert("guardado exitosamente")' class="btn-enviar">
            		<p class="form-link animated rubberBand">¿Ya tienes una cuenta? <a href="/login/">|Ingresa Aqui|</a>
				</div>
        		{% if form.errors %}<p style="text-align: center; color: #333;">{{ form.errors }}</p>{% endif %}
			</form>
		{% endblock  %}	
		</div>
	</div>
	
	<script src="/static/js/formulario.js"></script>
	
</body>
</html>